### PR TITLE
tests: Avoid actions' warnings

### PR DESCRIPTION
**Pull request by jcs090218**
Few CI improvements.

### CODE REVIEW

**Comment by xiliuya** [comment]
@NathanLovato This PR is ready to merge into master.

**Comment by xiliuya** [comment]
Hello, @jcs090218  Please `rebase` your PR.

**Comment by xiliuya** [comment]
Hello, @jcs090218  :
Thank you for your submission. After testing, there are errors in the code of your `rebase`, which can be repaired through the following patch:
```patch
diff --git a/Eask b/Eask
index 46e4c1e..5e62225 100644
--- a/Eask
+++ b/Eask
@@ -7,7 +7,6 @@
 
 (package-file "gdscript-mode.el")
 
-(package-file "gdscript-mode.el")
 (files "*.el")
 
 (script "test" "echo \"Error: no test specified\" && exit 1")
```

**Comment by jcs090218** [comment]
There is an error in current Windows snapshot, we can either:

1. ignore it
2. Add experimental flag, see https://github.com/emacs-lsp/lsp-mode/blob/5ec09d722ef153ceba0b0611cd208d5dbd06181f/.github/workflows/test.yml#L12-L31 for the example.

**Comment by xiliuya** [comment]
> 

I think it is more appropriate to Add experimental flag.

**Comment by xiliuya** [comment]
> There is an error in current Windows snapshot, we can either:
> 
>     1. ignore it
> 
>     2. Add experimental flag, see https://github.com/emacs-lsp/lsp-mode/blob/5ec09d722ef153ceba0b0611cd208d5dbd06181f/.github/workflows/test.yml#L12-L31 for the example.

Hello,@jcs090218.

I carefully checked the link you gave me. Will other `os` report an error after this flag is added?
If so then it would be more appropriate to ignore him.

**Comment by jcs090218** [comment]
It will still report the error but the badge and workflow will mark as passed (green).

**Comment by xiliuya** [comment]
> It will still report the error but the badge and workflow will mark as passed (green).

@jcs090218 Thank you for your prompt reply.
After your answer, I understand the Add experimental flag.
This is indeed a relatively good approach.
Would you like to include it in the subsequent submission or plan to have another PR submit it ？
If it is another PR, then I think it can already be merged into the master.

**Review by xiliuya — APPROVED** [review]
update Makefile for test.

**Comment by NathanLovato** [comment]
Thanks for the work!

**Pull request merged**
